/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../src/app/app-routing.module';
import * as i2 from './shop.component.ngfactory';
import * as i3 from './leases.component.ngfactory';
import * as i4 from './security.component.ngfactory';
import * as i5 from './securities.component.ngfactory';
import * as i6 from '@angular/router';
import * as i7 from '@angular/common';
import * as i8 from '../../../src/app/shop.component';
import * as i9 from '../../../src/app/leases.component';
import * as i10 from '../../../src/app/security.component';
import * as i11 from '../../../src/app/securities.component';
export const AppRoutingModuleNgFactory:i0.NgModuleFactory<i1.AppRoutingModule> = i0.ɵcmf(i1.AppRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.ShopComponentNgFactory,i3.LeasesComponentNgFactory,i4.SecurityComponentNgFactory,
              i5.SecuritiesComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(5120,i6.ActivatedRoute,i6.ɵf,[i6.Router]),i0.ɵmpd(4608,i6.NoPreloading,
              i6.NoPreloading,([] as any[])),i0.ɵmpd(6144,i6.PreloadingStrategy,(null as any),
              [i6.NoPreloading]),i0.ɵmpd(135680,i6.RouterPreloader,i6.RouterPreloader,
              [i6.Router,i0.NgModuleFactoryLoader,i0.Compiler,i0.Injector,i6.PreloadingStrategy]),
          i0.ɵmpd(4608,i6.PreloadAllModules,i6.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,
              i0.NgProbeToken,() => {
                return [i6.ɵb()];
              },([] as any[])),i0.ɵmpd(4608,i6.ɵg,i6.ɵg,[i0.Injector]),i0.ɵmpd(5120,
              i0.APP_INITIALIZER,(p0_0:any) => {
                return [i6.ɵh(p0_0)];
              },[i6.ɵg]),i0.ɵmpd(5120,i6.ROUTER_INITIALIZER,i6.ɵi,[i6.ɵg]),i0.ɵmpd(5120,
              i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
                return [p0_0];
              },[i6.ROUTER_INITIALIZER]),i0.ɵmpd(1024,i6.ɵa,i6.ɵd,[[3,i6.Router]]),
          i0.ɵmpd(512,i6.UrlSerializer,i6.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,
              i6.ChildrenOutletContexts,i6.ChildrenOutletContexts,([] as any[])),i0.ɵmpd(256,
              i6.ROUTER_CONFIGURATION,{},([] as any[])),i0.ɵmpd(1024,i7.LocationStrategy,
              i6.ɵc,[i7.PlatformLocation,[2,i7.APP_BASE_HREF],i6.ROUTER_CONFIGURATION]),
          i0.ɵmpd(512,i7.Location,i7.Location,[i7.LocationStrategy]),i0.ɵmpd(512,i0.NgModuleFactoryLoader,
              i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i6.ROUTES,() => {
            return [[{path:'',redirectTo:'/shop',pathMatch:'full'},{path:'shop',component:i8.ShopComponent},
                {path:'leases',component:i9.LeasesComponent},{path:'security',component:i10.SecurityComponent},
                {path:'securities',component:i11.SecuritiesComponent}]];
          },([] as any[])),i0.ɵmpd(1024,i6.Router,i6.ɵe,[i0.ApplicationRef,i6.UrlSerializer,
              i6.ChildrenOutletContexts,i7.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i6.ROUTES,i6.ROUTER_CONFIGURATION,[2,i6.UrlHandlingStrategy],
              [2,i6.RouteReuseStrategy]]),i0.ɵmpd(512,i6.RouterModule,i6.RouterModule,
              [[2,i6.ɵa],[2,i6.Router]]),i0.ɵmpd(512,i1.AppRoutingModule,i1.AppRoutingModule,
              ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvdmFncmFudC9nby9zcmMvZ2l0aHViLmNvbS9zZWV0aGVkYXRhL2JjbC9zcmMvYXBwL2FwcC1yb3V0aW5nLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL3ZhZ3JhbnQvZ28vc3JjL2dpdGh1Yi5jb20vc2VldGhlZGF0YS9iY2wvc3JjL2FwcC9hcHAtcm91dGluZy5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
