/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../src/app/app.module';
import * as i2 from '../../../src/app/app.component';
import * as i3 from './shop.component.ngfactory';
import * as i4 from './leases.component.ngfactory';
import * as i5 from './security.component.ngfactory';
import * as i6 from './securities.component.ngfactory';
import * as i7 from './app.component.ngfactory';
import * as i8 from '@angular/common';
import * as i9 from '@angular/platform-browser';
import * as i10 from 'angular-in-memory-web-api/interfaces';
import * as i11 from '../../../src/app/in-memory-data.service';
import * as i12 from '@angular/http';
import * as i13 from 'angular-in-memory-web-api/http-in-memory-web-api.module';
import * as i14 from '@angular/forms';
import * as i15 from '@angular/router';
import * as i16 from '@angular/common/http';
import * as i17 from 'angular-in-memory-web-api/http-client-in-memory-web-api.module';
import * as i18 from '../../../src/app/product.service';
import * as i19 from '../../../src/app/lease.service';
import * as i20 from '../../../src/app/security.service';
import * as i21 from 'angular-in-memory-web-api/in-memory-web-api.module';
import * as i22 from '../../../src/app/shop.component';
import * as i23 from '../../../src/app/leases.component';
import * as i24 from '../../../src/app/security.component';
import * as i25 from '../../../src/app/securities.component';
import * as i26 from '../../../src/app/app-routing.module';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.ShopComponentNgFactory,i4.LeasesComponentNgFactory,i5.SecurityComponentNgFactory,
              i6.SecuritiesComponentNgFactory,i7.AppComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),
          i0.ɵmpd(4608,i8.NgLocalization,i8.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(5120,
              i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,i0.IterableDiffers,i0.ɵk,
              ([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),
          i0.ɵmpd(4608,i9.DomSanitizer,i9.ɵe,[i8.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,
              (null as any),[i9.DomSanitizer]),i0.ɵmpd(4608,i9.HAMMER_GESTURE_CONFIG,
              i9.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,i9.EVENT_MANAGER_PLUGINS,
              (p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i9.ɵDomEventsPlugin(p0_0),new i9.ɵKeyEventsPlugin(p1_0),
                    new i9.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i8.DOCUMENT,i8.DOCUMENT,i8.DOCUMENT,i9.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i9.EventManager,i9.EventManager,[i9.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i9.ɵDomSharedStylesHost,i9.ɵDomSharedStylesHost,[i8.DOCUMENT]),
          i0.ɵmpd(4608,i9.ɵDomRendererFactory2,i9.ɵDomRendererFactory2,[i9.EventManager,
              i9.ɵDomSharedStylesHost]),i0.ɵmpd(6144,i0.RendererFactory2,(null as any),
              [i9.ɵDomRendererFactory2]),i0.ɵmpd(6144,i9.ɵSharedStylesHost,(null as any),
              [i9.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i0.Testability,i0.Testability,
              [i0.NgZone]),i0.ɵmpd(4608,i9.Meta,i9.Meta,[i8.DOCUMENT]),i0.ɵmpd(4608,
              i9.Title,i9.Title,[i8.DOCUMENT]),i0.ɵmpd(4608,i10.InMemoryDbService,
              i11.InMemoryDataService,([] as any[])),i0.ɵmpd(5120,i12.XHRBackend,i13.httpInMemBackendServiceFactory,
              [i0.Injector,i10.InMemoryDbService,i10.InMemoryBackendConfig]),i0.ɵmpd(4608,
              i12.RequestOptions,i12.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,
              i12.Http,i12.ɵc,[i12.XHRBackend,i12.RequestOptions]),i0.ɵmpd(4608,i12.BrowserXhr,
              i12.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i12.ResponseOptions,i12.BaseResponseOptions,
              ([] as any[])),i0.ɵmpd(5120,i12.XSRFStrategy,i12.ɵb,([] as any[])),i0.ɵmpd(4608,
              i14.ɵi,i14.ɵi,([] as any[])),i0.ɵmpd(5120,i15.ActivatedRoute,i15.ɵf,
              [i15.Router]),i0.ɵmpd(4608,i15.NoPreloading,i15.NoPreloading,([] as any[])),
          i0.ɵmpd(6144,i15.PreloadingStrategy,(null as any),[i15.NoPreloading]),i0.ɵmpd(135680,
              i15.RouterPreloader,i15.RouterPreloader,[i15.Router,i0.NgModuleFactoryLoader,
                  i0.Compiler,i0.Injector,i15.PreloadingStrategy]),i0.ɵmpd(4608,i15.PreloadAllModules,
              i15.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i15.ROUTER_INITIALIZER,
              i15.ɵi,[i15.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i15.ROUTER_INITIALIZER]),i0.ɵmpd(5120,i16.HttpBackend,i17.httpClientInMemBackendServiceFactory,
              [i10.InMemoryDbService,i10.InMemoryBackendConfig,i16.XhrFactory]),i0.ɵmpd(4608,
              i18.ProductService,i18.ProductService,[i12.Http]),i0.ɵmpd(4608,i19.LeaseService,
              i19.LeaseService,[i12.Http]),i0.ɵmpd(4608,i20.SecurityService,i20.SecurityService,
              [i12.Http]),i0.ɵmpd(512,i8.CommonModule,i8.CommonModule,([] as any[])),
          i0.ɵmpd(1024,i0.ErrorHandler,i9.ɵa,([] as any[])),i0.ɵmpd(1024,i0.NgProbeToken,
              () => {
                return [i15.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i15.ɵg,i15.ɵg,[i0.Injector]),i0.ɵmpd(1024,
              i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any) => {
                return [i9.ɵc(p0_0,p0_1),i15.ɵh(p1_0)];
              },[[2,i9.NgProbeToken],[2,i0.NgProbeToken],i15.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i9.BrowserModule,i9.BrowserModule,[[3,i9.BrowserModule]]),i0.ɵmpd(512,
              i12.HttpModule,i12.HttpModule,([] as any[])),i0.ɵmpd(512,i14.ɵba,i14.ɵba,
              ([] as any[])),i0.ɵmpd(512,i14.FormsModule,i14.FormsModule,([] as any[])),
          i0.ɵmpd(512,i21.InMemoryWebApiModule,i21.InMemoryWebApiModule,([] as any[])),
          i0.ɵmpd(1024,i15.ɵa,i15.ɵd,[[3,i15.Router]]),i0.ɵmpd(512,i15.UrlSerializer,
              i15.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,i15.ChildrenOutletContexts,
              i15.ChildrenOutletContexts,([] as any[])),i0.ɵmpd(256,i15.ROUTER_CONFIGURATION,
              {},([] as any[])),i0.ɵmpd(1024,i8.LocationStrategy,i15.ɵc,[i8.PlatformLocation,
              [2,i8.APP_BASE_HREF],i15.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i8.Location,
              i8.Location,[i8.LocationStrategy]),i0.ɵmpd(512,i0.Compiler,i0.Compiler,
              ([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,i0.SystemJsNgModuleLoader,
              [i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),i0.ɵmpd(1024,i15.ROUTES,
              () => {
                return [[{path:'',redirectTo:'/shop',pathMatch:'full'},{path:'shop',
                    component:i22.ShopComponent},{path:'leases',component:i23.LeasesComponent},
                    {path:'security',component:i24.SecurityComponent},{path:'securities',
                        component:i25.SecuritiesComponent}]];
              },([] as any[])),i0.ɵmpd(1024,i15.Router,i15.ɵe,[i0.ApplicationRef,i15.UrlSerializer,
              i15.ChildrenOutletContexts,i8.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i15.ROUTES,i15.ROUTER_CONFIGURATION,[2,i15.UrlHandlingStrategy],
              [2,i15.RouteReuseStrategy]]),i0.ɵmpd(512,i15.RouterModule,i15.RouterModule,
              [[2,i15.ɵa],[2,i15.Router]]),i0.ɵmpd(512,i26.AppRoutingModule,i26.AppRoutingModule,
              ([] as any[])),i0.ɵmpd(512,i1.AppModule,i1.AppModule,([] as any[])),
          i0.ɵmpd(256,i10.InMemoryBackendConfig,(undefined as any),([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvdmFncmFudC9nby9zcmMvZ2l0aHViLmNvbS9zZWV0aGVkYXRhL2JjbC9zcmMvYXBwL2FwcC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS92YWdyYW50L2dvL3NyYy9naXRodWIuY29tL3NlZXRoZWRhdGEvYmNsL3NyYy9hcHAvYXBwLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
