/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['a[_ngcontent-%COMP%]:link, a[_ngcontent-%COMP%]:hover, a[_ngcontent-%COMP%]:visited, a[_ngcontent-%COMP%]:active { text-decoration : none ; color : #000000 }\n\n.selected[_ngcontent-%COMP%] { background-color : #337ab7 ; color : #FFFFFF}\n\n.leases[_ngcontent-%COMP%] { width : 80% ; margin : auto ; border : solid ; padding : 1% ; margin-bottom : 1%}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvdmFncmFudC9nby9zcmMvZ2l0aHViLmNvbS9zZWV0aGVkYXRhL2JjbC9zcmMvYXBwL2xlYXNlcy5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvdmFncmFudC9nby9zcmMvZ2l0aHViLmNvbS9zZWV0aGVkYXRhL2JjbC9zcmMvYXBwL2xlYXNlcy5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
