/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['a[_ngcontent-%COMP%]:link, a[_ngcontent-%COMP%]:hover, a[_ngcontent-%COMP%]:visited, a[_ngcontent-%COMP%]:active { text-decoration : none ; color : #000000 }\n\n.productImage[_ngcontent-%COMP%] { height : 14em ; width : 11.8em ; margin: auto}\n.productPrice[_ngcontent-%COMP%] { font-size : 3em}\n\n.suffix[_ngcontent-%COMP%] { }'];
//# sourceMappingURL=products.component.css.shim.ngstyle.js.map