/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['a[_ngcontent-%COMP%]:link, a[_ngcontent-%COMP%]:hover, a[_ngcontent-%COMP%]:visited, a[_ngcontent-%COMP%]:active { text-decoration : none ; color : #000000 }\n\n.selected[_ngcontent-%COMP%] { background-color : #337ab7 !important;; color : #FFFFFF !important;}\n\n.security[_ngcontent-%COMP%] { margin : 0.3% ; color : #FFFFFF; background-color: #5cb85c ; width : 20%}\n\n.completed[_ngcontent-%COMP%] { background-color: #ABABAB; color : #000000}'];
//# sourceMappingURL=securities.component.css.shim.ngstyle.js.map