/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['a[_ngcontent-%COMP%]:link, a[_ngcontent-%COMP%]:hover, a[_ngcontent-%COMP%]:visited, a[_ngcontent-%COMP%]:active { text-decoration : none ; color : #000000 }\n\n.selected[_ngcontent-%COMP%] { background-color : #337ab7 ; color : #FFFFFF}\n\n#security[_ngcontent-%COMP%] { margin-top : 1% !important; padding : 1% ; border : solid ; width : 80% ; margin : auto }\n\n.leases[_ngcontent-%COMP%] { width : 80% ; margin : auto ; border : solid ; padding : 1% ; margin-bottom : 1%}'];
//# sourceMappingURL=security.component.css.shim.ngstyle.js.map