/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['a[_ngcontent-%COMP%]:link, a[_ngcontent-%COMP%]:hover, a[_ngcontent-%COMP%]:visited, a[_ngcontent-%COMP%]:active { text-decoration : none ; color : #000000 }\n\n.selected[_ngcontent-%COMP%] { background-color : #337ab7 ; color : #FFFFFF}\n\n#security[_ngcontent-%COMP%] { margin-top : 1% !important; padding : 1% ; border : solid ; width : 80% ; margin : auto }\n\n.leases[_ngcontent-%COMP%] { width : 80% ; margin : auto ; border : solid ; padding : 1% ; margin-bottom : 1%}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvdmFncmFudC9nby9zcmMvZ2l0aHViLmNvbS9zZWV0aGVkYXRhL2JjbC9zcmMvYXBwL3NlY3VyaXR5LmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS92YWdyYW50L2dvL3NyYy9naXRodWIuY29tL3NlZXRoZWRhdGEvYmNsL3NyYy9hcHAvc2VjdXJpdHkuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
